baseURL: http://zhazha.ch/
languageCode: en-us
title: Zha's blog
theme: ["PaperMod"]
caches:
  images:
    dir: :cacheDir/images




params:
  homeInfoParams:
    Title: About me
    Content: Can be Info, links, about...

