baseURL: http://zhazha.ch/
languageCode: en-us
title: Zha's blog
theme: ["PaperMod"]
caches:
  images:
    dir: :cacheDir/images




params:
  profileMode:
    enabled: true
    title: "<Title>" # optional default will be site title
    subtitle: "This is subtitle"
    imageUrl: "<image link>" # optional
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Archive
        url: "/archive"
      - name: Github
        url: "https://github.com/"
  homeInfoParams:
    Title: About me
    Content: Can be Info, links, about...

